SELECT * FROM TAB;

CREATE TABLE TBL_LINK
( LINK_NUM              NUMBER(5)
, LINK_TITLE               VARCHAR2(100)
, LINK_URL                  VARCHAR2(4000)
, LINK_DATE                 DATE
, CONSTRAINT PRIMARY_LINK_NUM PRIMARY KEY(LINK_NUM)
);

