SELECT * FROM TAB;

CREATE TABLE TBL_LINK
( LINK_NUM              NUMBER(5)
, LINK_TITLE               VARCHAR2(100)
, LINK_URL                  VARCHAR2(4000)
, LINK_DATE                 DATE
, CONSTRAINT PRIMARY_LINK_NUM PRIMARY KEY(LINK_NUM)
);

CREATE SEQUENCE SEQ_LINK_NUM NOCACHE;

INSERT INTO TBL_LINK(LINK_NUM, LINK_TITLE, LINK_URL, LINK_DATE) VALUES(SEQ_LINK_NUM.NEXTVAL, '네이버', 'http://www.naver.com', SYSDATE);

SELECT LINK_NUM, LINK_TITLE, LINK_URL, LINK_DATE FROM TBL_LINK;

commit;

SELECT LINK_NUM, LINK_TITLE, LINK_URL, LINK_DATE FROM TBL_LINK;


rollback;

	SELECT *
		FROM
		(
		SELECT DATA.*, ROWNUM AS RNUM FROM
		(SELECT LINK_NUM, LINK_TITLE, LINK_URL, LINK_DATE FROM TBL_LINK)DATA)
		WHERE #{start} <= RNUM AND RNUM <= #{end}

